### ISSUE TITLE
ScriptRunner crash OTD because of outdated opentabletdriver.plugin

### ISSUE THREAD

**Issue by GamuGamiChan** [X9VoiD/OTDPlugins#46]
### Steps to Reproduce

1. Bind a button to run a bat file
2. Apply and save everything
3. OTD crashed when button pressed

### Expected Behavior

Run the bat file

### Observed Behavior

OTD crashed with a error of
```
[MissingMethodException:Error]	Method not found: 'Void OpenTabletDriver.Plugin.Log.Exception(System.Exception)'.
   at VoiDPlugins.Binding.ScriptRunner.ScriptRunner.Press(TabletReference tablet, IDeviceReport report)
   at OpenTabletDriver.Desktop.Binding.BindingState.Invoke(TabletReference tablet, IDeviceReport report, Boolean newState) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.Desktop\Binding\BindingState.cs:line 19
   at OpenTabletDriver.Desktop.Binding.BindingHandler.HandleBindingCollection(TabletReference tablet, IDeviceReport report, IDictionary`2 bindings, IList`1 newStates) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.Desktop\Binding\BindingHandler.cs:line 80
   at OpenTabletDriver.Desktop.Binding.BindingHandler.HandleAuxiliaryReport(TabletReference tablet, IAuxReport report) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.Desktop\Binding\BindingHandler.cs:line 64
   at OpenTabletDriver.Desktop.Binding.BindingHandler.HandleBinding(IDeviceReport report) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.Desktop\Binding\BindingHandler.cs:line 46
   at OpenTabletDriver.Desktop.Binding.BindingHandler.Consume(IDeviceReport report) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.Desktop\Binding\BindingHandler.cs:line 37
   at Pressure_Debounce.Pressure_Debounce.Consume(IDeviceReport value)
   at OpenTabletDriver.Plugin.Output.OutputMode.Consume(IDeviceReport report) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.Plugin\Output\OutputMode.cs:line 113
   at OpenTabletDriver.Plugin.Output.AsyncPositionedPipelineElement`1.OnEmit() in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.Plugin\Output\AsyncPositionedPipelineElement.cs:line 121
   at TabletDriverFilters.Devocub.Antichatter.ConsumeState()
   at OpenTabletDriver.Plugin.Output.AsyncPositionedPipelineElement`1.Consume(T value) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.Plugin\Output\AsyncPositionedPipelineElement.cs:line 76
   at OpenTabletDriver.Plugin.Output.OutputMode.Read(IDeviceReport deviceReport) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.Plugin\Output\OutputMode.cs:line 115
   at OpenTabletDriver.InputDeviceTree.HandleReport(Object sender, IDeviceReport report) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver\InputDeviceTree.cs:line 63
   at OpenTabletDriver.Devices.DeviceReader`1.OnReport(T report) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver\Devices\DeviceReader.cs:line 140
   at OpenTabletDriver.Devices.DeviceReader`1.Main() in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver\Devices\DeviceReader.cs:line 111
```

### Tablet Device

Veikk VK430

### Diagnostic Information

[ScriptRunner.txt](https://github.com/X9VoiD/VoiDPlugins/files/14318454/ScriptRunner.txt)

**Comment by Oniicode** [comment]
Same here except i'm using an exe path to try to launch a program directly..

![image](https://github.com/X9VoiD/VoiDPlugins/assets/46069626/676584e2-799c-4097-9017-b607e39074b5)
![image](https://github.com/X9VoiD/VoiDPlugins/assets/46069626/1fe0f708-5cef-44f6-84c5-5e4684acfd23)

**Comment by GamuGamiChan** [comment]
Yeah I try every possible combination 
With quotes and no quotes
same directory as OTD 
nothing work

The error seem to find a directory named “a” in the D drive for some reason

@Oniicode is your error the same or not? There a copy all button

**Comment by GamuGamiChan** [comment]
I’m gonna fork this and see if I can fix this

**Comment by GamuGamiChan** [comment]
Seem like the Log.Exception(e) is missing because of opentabletdriver.plugin and need rebuilding

**Comment by noigamegun** [comment]
I builded it myself and it work now

@Oniicode here the files if you want (drag the zip file into the plugin manager) (make sure the broken scriptrunner plugin is uninstalled)

[ScriptRunner.zip](https://github.com/X9VoiD/VoiDPlugins/files/14320795/ScriptRunner.zip)

**Comment by noigamegun** [comment]
[ScriptRunner.zip](https://github.com/X9VoiD/VoiDPlugins/files/14321171/ScriptRunner.zip)

shrunk the file now it 9 kb instead of 80 kb

**Comment by GamuGamiChan** [comment]
@X9VoiD Any updates?
